<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-QDGOE72" ignored="0" name="Test" tests="10" failures="10" timestamp="19 Feb 2018 18:43:25 GMT" time="35.622" errors="0">
  <testcase name="testCase" time="7.37" classname="com.alg.test.executionengine.Executor">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.alg.test.executionengine.Executor.testCase(Executor.java:174)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testCase -->
  <testcase name="testCase" time="7.897" classname="com.alg.test.executionengine.Executor">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.alg.test.executionengine.Executor.testCase(Executor.java:174)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testCase -->
  <testcase name="testCase" time="13.933" classname="com.alg.test.executionengine.Executor">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.alg.test.executionengine.Executor.testCase(Executor.java:174)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testCase -->
  <testcase name="testCase" time="7.166" classname="com.alg.test.executionengine.Executor">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.alg.test.executionengine.Executor.testCase(Executor.java:174)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testCase -->
  <testcase name="testCase" time="7.137" classname="com.alg.test.executionengine.Executor">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.alg.test.executionengine.Executor.testCase(Executor.java:174)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testCase -->
  <testcase name="testCase" time="9.189" classname="com.alg.test.executionengine.Executor">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.alg.test.executionengine.Executor.testCase(Executor.java:174)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testCase -->
  <testcase name="testCase" time="9.33" classname="com.alg.test.executionengine.Executor">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.alg.test.executionengine.Executor.testCase(Executor.java:174)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testCase -->
  <testcase name="testCase" time="10.521" classname="com.alg.test.executionengine.Executor">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.alg.test.executionengine.Executor.testCase(Executor.java:174)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testCase -->
  <testcase name="testCase" time="10.167" classname="com.alg.test.executionengine.Executor">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.alg.test.executionengine.Executor.testCase(Executor.java:174)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testCase -->
  <testcase name="testCase" time="9.548" classname="com.alg.test.executionengine.Executor">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.alg.test.executionengine.Executor.testCase(Executor.java:174)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testCase -->
</testsuite> <!-- Test -->
